---
  - name: Update apt
    become: yes
    apt:  update_cache=yes

  - name: Install system packages
    become: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - curl
      - wget
      - build-essential
      - python-software-properties
      - htop
      - mc
      - git
      - lynx
      - links
