---
  - name: Init Kubernetes Cluster
    become: yes
    shell: kubeadm init > /kubeadm-init.txt

  - name: Allow Deploy pods to all nodes
    become: yes
    shell: kubectl taint nodes --all dedicated- > /taint-nodes.txt

  - name: Install Weave Network
    become: yes
    shell: kubectl apply -f https://git.io/weave-kube
